# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_auto_20170603_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sum',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='receipts',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.Receipt'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cash_total_sum',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ecash_total_sum',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='items',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.Item'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='kkt_reg_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_sum',
            field=models.IntegerField(blank=True),
        ),
    ]
