# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_auto_20170603_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='receipts',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.Receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
