# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_auto_20170603_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.Receipt'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='receipts.Profile'),
        ),
    ]
