# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_auto_20170603_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ndsNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='fiscalDocumentNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='fiscalDriveNumber',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='fiscalSign',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ndsNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='operationType',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='rawData',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receiptCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='requestNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='shiftNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='taxationType',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='userInn',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
