# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_auto_20170606_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='fiscalDocumentNumber',
            new_name='fiscal_document_number',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='fiscalDriveNumber',
            new_name='fiscal_drive_number',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='fiscalSign',
            new_name='fiscal_sign',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='ndsNo',
            new_name='nds_no',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='operationType',
            new_name='operation_type',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='rawData',
            new_name='raw_data',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='receiptCode',
            new_name='receipt_code',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='requestNumber',
            new_name='request_number',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='shiftNumber',
            new_name='shift_number',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='taxationType',
            new_name='taxation_type',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='userInn',
            new_name='user_inn',
        ),
    ]
