# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_auto_20170607_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='kkt_reg_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
