# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0011_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclude',
            name='item',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='exclude',
            name='user',
            field=models.BigIntegerField(),
        ),
    ]
