# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0012_auto_20170615_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclude',
            name='item',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exclude',
            name='user',
            field=models.BigIntegerField(blank=True),
        ),
    ]
