# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0014_auto_20170615_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='exclude',
            field=models.BooleanField(default=True),
        ),
    ]
