# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0015_item_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
